sources:
  tiktok:
    enabled: true # default: true
    subresources:
      video:
        tool: yt-dlp
        url-patterns:
          - ^https?://([a-z0-9-]+\.)?tiktok\.com/@[^/]+/video/\d+/?(?:[?#].*)?$
          - ^https?://([a-z0-9-]+\.)?tiktok\.com/video/\d+/?(?:[?#].*)?$
      photo:
        tool: gallery-dl
        url-patterns:
          - ^https?://([a-z0-9-]+\.)?tiktok\.com/@[^/]+/photo/\d+/?(?:[?#].*)?$
          - ^https?://([a-z0-9-]+\.)?tiktok\.com/photo/\d+/?(?:[?#].*)?$
  instagram:
    subresources:
      reels:
        tool: yt-dlp
        url-patterns:
          - ^https?://([a-z0-9-]+\.)?instagram\.com/reels?/[A-Za-z0-9_-]{5,}/?(?:[?#].*)?$
      posts:
        tool: gallery-dl
        url-patterns:
          - ^https?://([a-z0-9-]+\.)?instagram\.com/p/[A-Za-z0-9_-]{5,}/?(?:[?#].*)?$
  some-extraordinary-source:
    enabled: false
    subresources:
      subresource:
        tool: magic-tool
        url-patterns:
          - 'xxx'
          - 'xxx'
  youtube:
    enabled: true
    subresources:
      shorts:
        tool: yt-dlp
        url-patterns:
          - ^https?://(?:www\.|m\.)?youtube\.com/shorts/[A-Za-z0-9_-]{11}/?(?:[?#].*)?$
          - ^https?://(?:www\.|m\.)?youtube\.com/@[^/]+/shorts/[A-Za-z0-9_-]{11}/?(?:[?#].*)?$